$:
  vscode:
    - runner:
        cpus: 2
      docker:
        image: cnbcool/default-dev-env:latest
      services:
        - vscode
        - docker
      stages:
        - name: 配置镜像
          script: npm config set registry https://mirrors.cloud.tencent.com/npm/
        - name: 安装 PNPM
          script: npm install -g pnpm
        - name: 安装依赖
          script: pnpm i
        - name: 关联 .env
          script: cp -f /root/.cnb/.env ./apps/api 2>/dev/null || echo "文件不存在"